name: Cliamizer
description: A new Flutter application.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_animation_tabbar: ^0.0.1
  intl_phone_field: ^3.1.0
  google_fonts:
  conditional_builder:
  flutter_staggered_animations: "^1.0.0"
  sizer:
  share:
  solid_bottom_sheet:
  device_preview:
  chewie: ^1.3.3
  video_player:
  flutter_localizations:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons:
  # Dart 常用工具类库 https://github.com/Sky24n/common_utils
  common_utils: ^2.0.2
  # Flutter
  flustars: ^2.0.1

  # Flutter
  fluintl: ^2.0.0

  #https://github.com/dart-lang/intl
  intl: ^0.17.0
  modal_bottom_sheet: ^2.0.1
  responsive_builder: ^0.4.2
  #charts_flutter:
  # https://github.com/flutterchina/dio
  dio: ^4.0.0

  #https://github.com/dart-lang/http_parser
  http_parser: ^4.0.0
#
  # rxdart https://github.com/ReactiveX/rxdart
  rxdart: ^0.27.5
#
#  # https://github.com/renefloor/flutter_cached_network_image
  #  cached_network_image: ^1.1.3
  cached_network_image: ^3.0.0
#
#  #shared_preferences https://github.com/flutter/plugins/tree/master/packages/shared_preferences/shared_preferences
  shared_preferences: ^2.0.5
#
#  #Social Auth
  google_sign_in: ^5.0.2
#  flutter_facebook_login: ^3.0.0
  flutter_facebook_auth: ^4.1.1

#
#  # https://github.com/flutter/plugins/tree/master/packages/url_launcher
  url_launcher: ^6.0.3
#
#   https://github.com/peng8350/flutter_pulltorefresh
  pull_to_refresh: ^2.0.0

  # sprintf String https://github.com/Naddiseo/dart-sprintf
  sprintf: ^6.0.0

  # https://github.com/flutterchina/flukit.
  flukit: ^1.0.0
  #状态管理
  provider: ^6.0.0

  # Toast插件 https://github.com/OpenFlutter/flutter_oktoast
  oktoast: ^3.0.0

  # fluro https://github.com/theyakka/fluro
  fluro: ^2.0.3
  #
  # flutter_keyboard_actions https://github.com/diegoveloper/flutter_keyboard_actions
  keyboard_actions: ^3.4.0
  #
  #  #https://github.com/marcojakob/dart-event-bus
  event_bus: ^2.0.0

  #package_info https://github.com/flutter/plugins/tree/master/packages/package_info
  package_info: ^2.0.0

  # https://github.com/flutter/plugins/tree/master/packages/webview_flutter
  webview_flutter:

  #https://github.com/leisim/logger.git  日志工具
  logger: ^1.0.0

  #https://github.com/dart-lang/http
  http: ^0.13.1

  flutter_styled_toast: ^2.1.3
  shimmer: ^2.0.0
  toast: ^0.1.5
  flutter_spinkit: ^5.1.0
  flutter_svg: ^0.23.0
  syncfusion_flutter_datepicker: ^19.4.56
  flutter_map: ^0.14.0
  flutter_screenutil: ^5.4.0
  phone_form_field:
  phone_numbers_parser:
  auto_size_text: ^3.0.0
  lottie: ^1.3.0
  device_info_plus: any
  dropdown_search: ^3.0.1
  smooth_page_indicator: ^1.0.1
  carousel_slider: ^4.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0


flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/ic_launcher.png"




flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/svg/
    - assets/images/png/


  fonts:
  - family: Tajawal
    fonts:
      - asset: assets/fonts/Tajawal-Black.ttf
        weight: 400
      - asset: assets/fonts/Tajawal-Bold.ttf
        weight: 500
      - asset: assets/fonts/Tajawal-Light.ttf
        weight: 100
      - asset: assets/fonts/Tajawal-Medium.ttf
        weight: 300
      - asset: assets/fonts/Tajawal-Regular.ttf
        weight: 200
  - family: AirbnbCereal
    fonts:
      - asset: assets/fonts/AirbnbCereal_W_Bd.otf
        weight: 600
      - asset: assets/fonts/AirbnbCereal_W_Bk.otf
        weight: 500
      - asset: assets/fonts/AirbnbCereal_W_Blk.otf
        weight: 400
      - asset: assets/fonts/AirbnbCereal_W_Lt.otf
        weight: 300
      - asset: assets/fonts/AirbnbCereal_W_Md.otf
        weight: 200
      - asset: assets/fonts/AirbnbCereal_W_XBd.otf
        weight: 100
  - family: PFBagueRoundPro
    fonts:
      - asset: assets/fonts/PFBagueRoundPro-Light.ttf
        weight: 200
      - asset: assets/fonts/PFBagueRoundPro-Regular.ttf
        weight: 400
      - asset: assets/fonts/PFBagueRoundPro-Medium.ttf
        weight: 500
      - asset: assets/fonts/PFBagueRoundPro-Bold.ttf
        weight: 600


flutter_intl:
  enabled: true